failed to fetch

diff --git a/.github/workflows/feature-catalog.yml b/.github/workflows/feature-catalog.yml
--- a/.github/workflows/feature-catalog.yml
+++ b/.github/workflows/feature-catalog.yml
@@ -42,6 +42,12 @@ jobs:
         run: |
           ALL_CHANGED_FILES=$(curl -s -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files" | jq -r '.[].filename' | paste -sd, -)
+          echo "Endpoint https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files"
+          echo "All changed files $ALL_CHANGED_FILES"
+          if [ -z "$ALL_CHANGED_FILES" ]; then
+            echo "Failed to fetch files changed in this PR"
+            exit 1
+          fi
           echo "all_changed_files=$ALL_CHANGED_FILES" >> $GITHUB_OUTPUT
 
       - name: Set up Python
